# Generated by Django 4.1.4 on 2023-01-30 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation_Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CASE_ID', models.IntegerField()),
                ('Status', models.CharField(max_length=50)),
                ('Investigator_ID', models.IntegerField()),
                ('Investigator_Name', models.CharField(max_length=50)),
                ('Investigator_Office_Code', models.CharField(max_length=50)),
                ('Investigator_Report', models.TextField()),
                ('Date_and_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Investigator_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nick_Name', models.CharField(max_length=50)),
                ('Pass_Word', models.IntegerField()),
                ('District', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Office_Code', models.CharField(max_length=50)),
                ('Contact_Num', models.CharField(max_length=50)),
                ('Image', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50)),
                ('Pass_Word', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nick_Name', models.CharField(max_length=50)),
                ('Pass_Word', models.IntegerField()),
                ('Security_Question', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Contact_Num', models.CharField(max_length=50)),
                ('Blocked', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_and_time', models.DateField()),
                ('Report_text', models.TextField()),
                ('Proof_Image', models.CharField(max_length=100)),
                ('Proof_clip', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=50)),
                ('Reporter_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MNCSApp.registration')),
            ],
        ),
    ]
