# Generated by Django 4.1.4 on 2023-02-03 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MNCSApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime_Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_and_time', models.DateField()),
                ('Report_text', models.TextField()),
                ('Proof_Image', models.CharField(max_length=100)),
                ('Proof_clip', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=50)),
                ('Investigator_ID', models.IntegerField(null=True)),
                ('Reporter_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MNCSApp.registration')),
            ],
        ),
    ]
